// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeH-Kq0jpFmYn6Poo99SI_5n4QIihIHCQ',
    appId: '1:1060646689103:web:abe44ff322582b26348d3a',
    messagingSenderId: '1060646689103',
    projectId: 'sobanhang-cacc3',
    authDomain: 'sobanhang-cacc3.firebaseapp.com',
    storageBucket: 'sobanhang-cacc3.firebasestorage.app',
    measurementId: 'G-E15S3GH1R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUMwDbSoHu2_bvDH3LRfw2xVXpY39Fr3E',
    appId: '1:1060646689103:android:0be0850c7e55593a348d3a',
    messagingSenderId: '1060646689103',
    projectId: 'sobanhang-cacc3',
    storageBucket: 'sobanhang-cacc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtAe9BmvLOjhrloC7JhyGxLN0biakftqc',
    appId: '1:1060646689103:ios:2fe97bd7aa547b03348d3a',
    messagingSenderId: '1060646689103',
    projectId: 'sobanhang-cacc3',
    storageBucket: 'sobanhang-cacc3.firebasestorage.app',
    iosBundleId: 'com.example.sobanhang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtAe9BmvLOjhrloC7JhyGxLN0biakftqc',
    appId: '1:1060646689103:ios:2fe97bd7aa547b03348d3a',
    messagingSenderId: '1060646689103',
    projectId: 'sobanhang-cacc3',
    storageBucket: 'sobanhang-cacc3.firebasestorage.app',
    iosBundleId: 'com.example.sobanhang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeH-Kq0jpFmYn6Poo99SI_5n4QIihIHCQ',
    appId: '1:1060646689103:web:3a3503bc01f247f0348d3a',
    messagingSenderId: '1060646689103',
    projectId: 'sobanhang-cacc3',
    authDomain: 'sobanhang-cacc3.firebaseapp.com',
    storageBucket: 'sobanhang-cacc3.firebasestorage.app',
    measurementId: 'G-H30VR8NXFQ',
  );
}
